export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const SET_IMAGE_URL = 'SET_IMAGE_URL';
export const SET_IMAGES_FROM_STORE = 'SET_IMAGES_FROM_STORE';
